services:
  nginx:
    image: nginx:alpine
    container_name: imagine_chat_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - imagine_chat_network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: imagine_chat_php
    volumes:
      - ./:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-chat_app}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    depends_on:
      - postgres
    networks:
      - imagine_chat_network

  postgres:
    image: postgres:18.1-alpine
    container_name: imagine_chat_postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE:-chat_app}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - imagine_chat_network

networks:
  imagine_chat_network:
    driver: bridge
    name: imagine_chat_network

# prevent data loss if the postgres container is eventually removed
volumes:
  postgres_data:
    name: postgres_data
